version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
automerge_label = ["dependencies", "status: ready to merge 🎉"]
title = "pull_request_title"
body = "pull_request_body"

[update]
always = true
require_automerge_label = false
ignored_usernames = ["dependabot"]
