version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
      - run:
          name: Install dependencies 
          command: PATH=$HOME/.yarn/bin:$PATH yarn install
      - run:
          name: Run Continuous Integration checks
          command: PATH=$HOME/.yarn/bin:$PATH yarn ci-check
      - run:
          name: Confirm project can build
          command: |
            PATH=$HOME/.yarn/bin:$PATH yarn build:prefix
      - deploy:
          name: deploy website to IBM Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install `ibmcloud` CLI
              curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

              # Login and push to us
              ibmcloud login \
                --apikey $CLOUD_API_KEY \
                -a https://api.ng.bluemix.net \
                -o IBMDesignOrg \
                -s idl

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              ibmcloud cf blue-green-deploy design-language-staging-alison  \
                -f .circleci/manifest.staging.yml \
                --delete-old-apps

              # Login and push to germany
              ibmcloud login \
                --apikey $CLOUD_API_KEY \
                -a https://api.eu-de.bluemix.net \
                -o IBMDesignOrg \
                -s idl

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              ibmcloud cf blue-green-deploy design-language-staging-alison  \
                -f .circleci/manifest.staging.yml \
                --delete-old-apps
            fi
