version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run Continuous Integration checks
          command: yarn ci-check
      - run:
          name: Confirm project can build
          command: yarn build:prefix
      - deploy:
          name: deploy website to IBM Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # Install `ibmcloud` CLI
              curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

              # Login and push to us
              ibmcloud login \
                --apikey $API_KEY_IDL \
                -a https://api.ng.bluemix.net \
                -o IBMDesignOrg \
                -s idl

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              ibmcloud cf blue-green-deploy design-language-website-carbon  \
                -f .circleci/manifest.production.yml \
                --delete-old-apps

              # Login and push to germany
              ibmcloud login \
                --apikey $API_KEY_IDL \
                -a https://api.eu-de.bluemix.net \
                -o IBMDesignOrg \
                -s idl

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              ibmcloud cf blue-green-deploy design-language-website-carbon  \
                -f .circleci/manifest.production.yml \
                --delete-old-apps
            fi
